
TYPE
	
	STATE_SKI : 
		(
		STATE_SKI_WAIT,
		STATE_SKI_TOP,
		STATE_SKI_TURN,
		STATE_SKI_BOTTOM
	);
	STATE : 
		(
		STATE_WAIT,
		STATE_HIDE_NEW_MATERIAL,
		STATE_REMOVE_PISTON,
		STATE_REMOVE_UNIT,
		STATE_REMOVE_CLAMP,
		STATE_REMOVE_PART_1,
		STATE_REMOVE_PART_2,
		STATE_HIDE_PART,
		STATE_APPLY_PART,
		STATE_APPLY_CLAMP,
		STATE_APPLY_UNIT,
		STATE_APPLY_PISTON,
		STATE_SHOW_NEW_MATERIAL,
		STATE_SHOW_PART
	);
	
	STATE_BOX : 
		(
		STATE_INIT,
		STATE_SHOW_BOX,
		STATE_LIFT_MOVE_UP,
		STATE_LIFT_OPEN_LEFT,
		STATE_LIFT_MOVE_LEFT,
		STATE_LIFT_CLOSE_LEFT,
		STATE_BOTH_MOVE_RIGHT,
		STATE_BOTH_MOVE_DOWN,
		STATE_LIFT_OPEN_RIGHT,
		STATE_BOX_MOVE_RIGHT,
		STATE_CONV_MOVE_RIGHT,
		STATE_LIFT_CLOSE_RIGHT,
		STATE_LIFT_BOX_INIT
	);
END_TYPE
